### ISSUE TITLE
License for this project?

### ISSUE THREAD

**Issue by ag1le** [testdrivenio/django-ecs-terraform#10]
I see that most [testdrivenio](https://github.com/testdrivenio) repos have MIT License  but this repo has none.  I would like to use this example as a basis for a small project, but without license there is no point. 

Do you think you could add MIT  License for this repo as well? 

BTW - Are you going to create a course about this project in here https://testdriven.io/courses/ ? I would like to buy it but didn't see it there.

**Comment by mjhea0** [comment]
Just added - https://github.com/testdrivenio/django-ecs-terraform/blob/master/LICENSE.

Not planning on doing any courses any time soon on Django and ECS. We do have other ECS-based courses that might be helpful, though:

1. https://testdriven.io/courses/aws-flask-react/
2. https://testdriven.io/courses/scalable-flask-aws/
3. https://testdriven.io/courses/scalable-fastapi-aws/
