### ISSUE TITLE
can't reach via ssh my ec2 instance - I think the cause is due to the vpc.

### ISSUE THREAD

**Issue by drandredev** [testdrivenio/django-ecs-terraform#12]
![image](https://user-images.githubusercontent.com/67886654/162804376-b3c69264-2810-45ce-9a5a-872ac7216f85.png)

**Comment by cugarteblair** [comment]
I had the same issue. Did you ever resolve this?

**Comment by cugarteblair** [comment]
I temporarily changed the route table. Change the entry that routes to the NAT gateway route; Make it route to the internet gateway instead. Then you can access the private subnets for SSH. When you are done restore the route.

**Comment by tarkin88** [comment]
> I temporarily changed the route table. Change the entry that routes to the NAT gateway route; Make it route to the internet gateway instead. Then you can access the private subnets for SSH. When you are done restore the route.

Can you post an example, please?

**Comment by Cguilliman** [comment]
For me this temporary solution is working
```
resource "aws_route" "nat-gw-route" {
  route_table_id         = aws_route_table.private-route-table.id
  # nat_gateway_id         = aws_nat_gateway.nat-gw.id
  gateway_id             = aws_internet_gateway.production-igw.id
  destination_cidr_block = "0.0.0.0/0"
}
```
