### ISSUE TITLE
After deploying, staticfiles are not showing up.

### ISSUE THREAD

**Issue by benedictchen** [testdrivenio/django-ecs-terraform#2]
It appears after deploying and ssh'ing into one of the machines, the directory specified for the static files: `/usr/src/app/staticfiles/` is not showing anything inside.  If I run the command after docker is pushed and the image is swapped, then the files show up without issue.  However, just running the deploy scripts and pushing the new images doesn't seem to do anything.

**Comment by mjhea0** [comment]
addressing via email

**Comment by caeser1996** [comment]
can you please help me as well ? @mjhea0
